name: Varangian Guard

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch: # Allows manual triggering

concurrency: safe-tx-relayer

jobs:
  fetch-check-relay:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: safe-research/varangian

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Cache npm dependencies for faster builds
          cache-dependency-path: 'actions/package-lock.json'

      - name: Install All Dependencies (using workspaces)
        working-directory: actions
        run: npm install

      - name: Build
        working-directory: actions
        run: npm run build:all

      - name: Fetch Tx
        id: fetch-tx
        uses: ./actions/fetch-tx 
        with:
          safe-address: ${{ secrets.SAFE_ADDRESS }}
          service-url: ${{ secrets.SERVICE_URL }}

      - name: Check Tx
        id: check-tx
        uses: ./actions/check 
        with:
          co-signer-material: ${{ secrets.COSIGNER_MATERIAL }}
          safe-tx: ${{ steps.fetch-tx.outputs.safe-tx }}

      - name: Relay Tx
        id: relay
        if: ${{ steps.fetch-tx.outputs.safe-tx != '' }}
        uses: ./actions/relay 
        with:
          co-signer-signature: ${{ steps.check-tx.outputs.co-signer-signature }}
          safe-tx: ${{ steps.fetch-tx.outputs.safe-tx }}
